[build]
  command = "npm run build"
  publish = "dist/public"
  
  # Force cache invalidation
  NETLIFY_CACHE_ID = "maszynownia-v3-2025-09-05"

[build.environment]
  NODE_VERSION = "18"
  CACHE_BUST_VERSION = "2025-09-05-v3"
  FORCE_REBUILD = "2025-09-05-14:30:00"

# Force fresh assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]  
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200